spring:
  application:
    name: product-service
  datasource:
#    url: jdbc:postgresql://localhost:5432/product?stringtype=unspecified&options=-c%20TimeZone=Asia/Ho_Chi_Minh
    url: jdbc:postgresql://ep-empty-frog-adnk2qcx-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
    username: neondb_owner
    password: npg_HYj8xusqAc2p
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081
