spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://localhost:5432/product?stringtype=unspecified&options=-c%20TimeZone=Asia/Ho_Chi_Minh
    username: dungngaongo
    password: cungvay10
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create

server:
  port: 8081
